tasks:
  - init: >
        cd /workspace/reservy/frontend &&
        npm install &&
        npm install -g @angular/cli@7.3.9
    command: >
        cd /workspace/reservy/frontend &&
        npm start
  - init: >
        cd /workspace/reservy/api/core &&
        composer install
    command: >
        cd /workspace/reservy &&
        php -S localhost:8080